### ISSUE TITLE
Discussion: Opensource  Licence for monero-docs

### ISSUE THREAD

**Issue by dan-is-not-the-man** [monero-project/monero-docs#17]
Just creating this so we can track what has been brung up in monero-website and monero-docs rooms

I found these :

- https://opensource.guide/legal/#just-give-me-the-tldr-on-what-i-need-to-protect-my-project
- https://choosealicense.com/

Currently: https://github.com/monero-project/monero-docs/pull/11

**Comment by nahuhh** [comment]
After some discussion and consulting, it seems best to stick with monerodocs MIT license for the content of the `/docs` folder

https://github.com/monero-project/monero-docs/pull/19
