### ISSUE TITLE
Enable github boards for thingsto-do/roadmap

### ISSUE THREAD

**Issue by dan-is-not-the-man** [monero-project/monero-docs#3]
Can we enable github boards for this repo

- https://github.com/features/issues

Intructions:
- https://github.blog/developer-skills/github/getting-started-with-project-planning-on-github/

e.g. https://github.com/orgs/github/projects/4247/views/7

![docs](https://github.com/user-attachments/assets/b3a88881-abbd-4da0-800d-dab4a9082dae)

**Comment by detherminal** [comment]
@luigi1111

**Comment by luigi1111** [comment]
I created one and invited you. You should be able to edit it.

**Comment by dan-is-not-the-man** [comment]
who is that at?

**Comment by luigi1111** [comment]
Whoops. I can't find you in the add collaborator page. Not sure how to fix that.

**Comment by luigi1111** [comment]
Oh I guess you need to be added to a repo first.
